-- Autonomous Image Acquisition Orchestrator Database Schema
-- This creates the trigger-based infrastructure for self-sustaining pipelines

-- Table 1: Julius AI Ingest Events (Julius writes discoveries here)
CREATE TABLE IF NOT EXISTS julius_ingest_events (
    id SERIAL PRIMARY KEY,
    event_type VARCHAR(50) NOT NULL,  -- 'image_discovered', 'metadata_found', 'source_identified'
    scientific_name VARCHAR(255),
    source_url TEXT,
    image_urls JSONB,  -- Array of image URLs discovered
    metadata JSONB,    -- Any metadata discovered
    priority INTEGER DEFAULT 5,
    status VARCHAR(20) DEFAULT 'pending',  -- 'pending', 'processing', 'completed', 'failed'
    created_at TIMESTAMP DEFAULT NOW(),
    processed_at TIMESTAMP,
    pipeline_assigned VARCHAR(50)  -- Which pipeline should handle this
);

-- Table 2: Pipeline Tasks Queue (Auto-generated by triggers)
CREATE TABLE IF NOT EXISTS pipeline_tasks (
    id SERIAL PRIMARY KEY,
    task_type VARCHAR(50) NOT NULL,  -- 'eol_gbif', 'institutional', 'ai_discovery'
    scientific_name VARCHAR(255) NOT NULL,
    priority INTEGER DEFAULT 5,
    source_event_id INTEGER REFERENCES julius_ingest_events(id),
    status VARCHAR(20) DEFAULT 'queued',  -- 'queued', 'running', 'completed', 'failed'
    retry_count INTEGER DEFAULT 0,
    max_retries INTEGER DEFAULT 3,
    task_data JSONB,
    created_at TIMESTAMP DEFAULT NOW(),
    started_at TIMESTAMP,
    completed_at TIMESTAMP,
    assigned_worker VARCHAR(100),
    error_message TEXT,
    UNIQUE(task_type, scientific_name, status)  -- Prevent duplicate queued tasks
);

-- Table 3: Image Assets (Unified storage for all pipeline outputs)
CREATE TABLE IF NOT EXISTS image_assets (
    id SERIAL PRIMARY KEY,
    scientific_name VARCHAR(255) NOT NULL,
    genus VARCHAR(100),
    species VARCHAR(100),
    local_path TEXT NOT NULL,
    original_url TEXT,
    perceptual_hash VARCHAR(64),  -- For duplicate detection
    source VARCHAR(50),  -- 'EOL', 'GBIF', 'iNaturalist', etc.
    source_url TEXT,
    license VARCHAR(100),
    attribution TEXT,
    pipeline VARCHAR(50),  -- Which pipeline acquired this
    quality_score FLOAT,
    width INTEGER,
    height INTEGER,
    file_size INTEGER,
    metadata JSONB,
    created_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(perceptual_hash)  -- Prevent exact duplicates
);

-- Table 4: Orchestration Status (Tracks pipeline health and coverage)
CREATE TABLE IF NOT EXISTS orchestration_status (
    id SERIAL PRIMARY KEY,
    metric_name VARCHAR(100) NOT NULL,
    metric_value JSONB,
    updated_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(metric_name)
);

-- Table 5: Worker Heartbeats (Track which workers are alive)
CREATE TABLE IF NOT EXISTS worker_heartbeats (
    worker_id VARCHAR(100) PRIMARY KEY,
    worker_type VARCHAR(50),
    status VARCHAR(20),  -- 'running', 'idle', 'dead'
    last_heartbeat TIMESTAMP DEFAULT NOW(),
    tasks_processed INTEGER DEFAULT 0,
    current_task JSONB
);

-- TRIGGER 1: When Julius discovers something, create pipeline tasks
CREATE OR REPLACE FUNCTION trigger_pipeline_tasks()
RETURNS TRIGGER AS $$
BEGIN
    -- Create task based on event type
    IF NEW.event_type = 'image_discovered' THEN
        INSERT INTO pipeline_tasks (
            task_type, 
            scientific_name, 
            priority,
            source_event_id,
            task_data
        ) VALUES (
            NEW.pipeline_assigned,
            NEW.scientific_name,
            NEW.priority,
            NEW.id,
            NEW.metadata
        )
        ON CONFLICT (task_type, scientific_name, status) DO NOTHING;
        
        -- Send NOTIFY to wake up workers
        PERFORM pg_notify('pipeline_task_created', NEW.pipeline_assigned || ':' || NEW.scientific_name);
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS julius_ingest_trigger ON julius_ingest_events;
CREATE TRIGGER julius_ingest_trigger
    AFTER INSERT ON julius_ingest_events
    FOR EACH ROW
    EXECUTE FUNCTION trigger_pipeline_tasks();

-- TRIGGER 2: When image acquired, update metrics and check if more work needed
CREATE OR REPLACE FUNCTION trigger_orchestration_update()
RETURNS TRIGGER AS $$
DECLARE
    total_images INTEGER;
    coverage_pct FLOAT;
BEGIN
    -- Update coverage metrics
    SELECT COUNT(*) INTO total_images FROM image_assets;
    
    INSERT INTO orchestration_status (metric_name, metric_value)
    VALUES (
        'total_images_acquired',
        jsonb_build_object(
            'count', total_images,
            'last_updated', NOW(),
            'last_source', NEW.source,
            'last_pipeline', NEW.pipeline
        )
    )
    ON CONFLICT (metric_name) DO UPDATE
    SET metric_value = EXCLUDED.metric_value,
        updated_at = NOW();
    
    -- Notify orchestrator to check if more work needed
    PERFORM pg_notify('image_acquired', NEW.pipeline || ':' || NEW.scientific_name);
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS image_asset_trigger ON image_assets;
CREATE TRIGGER image_asset_trigger
    AFTER INSERT ON image_assets
    FOR EACH ROW
    EXECUTE FUNCTION trigger_orchestration_update();

-- TRIGGER 3: When task completed, update status and notify orchestrator
CREATE OR REPLACE FUNCTION trigger_task_completion()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.status = 'completed' AND OLD.status != 'completed' THEN
        -- Update julius event status
        UPDATE julius_ingest_events 
        SET status = 'completed', processed_at = NOW()
        WHERE id = NEW.source_event_id;
        
        -- Notify orchestrator
        PERFORM pg_notify('task_completed', NEW.task_type || ':' || NEW.scientific_name);
    END IF;
    
    IF NEW.status = 'failed' AND NEW.retry_count < NEW.max_retries THEN
        -- Auto-retry failed tasks
        UPDATE pipeline_tasks
        SET status = 'queued', retry_count = retry_count + 1
        WHERE id = NEW.id;
        
        PERFORM pg_notify('task_retry', NEW.task_type || ':' || NEW.scientific_name);
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS task_completion_trigger ON pipeline_tasks;
CREATE TRIGGER task_completion_trigger
    AFTER UPDATE ON pipeline_tasks
    FOR EACH ROW
    EXECUTE FUNCTION trigger_task_completion();

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_julius_events_status ON julius_ingest_events(status, priority DESC);
CREATE INDEX IF NOT EXISTS idx_pipeline_tasks_status ON pipeline_tasks(status, priority DESC, created_at);
CREATE INDEX IF NOT EXISTS idx_image_assets_scientific ON image_assets(scientific_name);
CREATE INDEX IF NOT EXISTS idx_image_assets_hash ON image_assets(perceptual_hash);
CREATE INDEX IF NOT EXISTS idx_worker_heartbeats_status ON worker_heartbeats(status, last_heartbeat);

-- Function to get advisory lock for species (prevents duplicate work)
CREATE OR REPLACE FUNCTION acquire_species_lock(species_name VARCHAR) 
RETURNS BOOLEAN AS $$
BEGIN
    RETURN pg_try_advisory_lock(hashtext(species_name));
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION release_species_lock(species_name VARCHAR) 
RETURNS BOOLEAN AS $$
BEGIN
    RETURN pg_advisory_unlock(hashtext(species_name));
END;
$$ LANGUAGE plpgsql;
